spring.application.name=chat
jwt.public-key.location=classpath:public-key.pem
logging.level.org.springframework.web=DEBUG
aws.sdk.dynamo-db.url=http://${DYNAMODB_HOST}:${DYNAMODB_PORT}
aws.sdk.dynamo-db.table=${DYNAMODB_TABLE}
