spring.application.name=chat
jwt.public-key.location=classpath:public-key.pem
logging.level.org.springframework.web=DEBUG
app.rabbitmq.stomp.host=${RABBITMQ_HOST}
app.rabbitmq.stomp.port=${RABBITMQ_STOMP_RELAY_PORT}
