spring.application.name=chat
jwt.public-key.location=classpath:public-key.pem
logging.level.org.springframework.web=DEBUG

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

app.rabbitmq.stomp.host=${RABBITMQ_HOST}
app.rabbitmq.stomp.port=${RABBITMQ_STOMP_RELAY_PORT}
