spring.application.name=dispatcher
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.listener.simple.missing-queues-fatal=false
aws.sdk.dynamo-db.url=http://${DYNAMODB_HOST}:${DYNAMODB_PORT}
aws.sdk.dynamo-db.table=${DYNAMODB_TABLE}
services.conversations.url=${CONVERSATIONS_API_URI}
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
logging.level.software.amazon.awssdk=DEBUG
logging.level.software.amazon.awssdk.request=DEBUG
logging.level.org.apache.http.wire=DEBUG
logging.level.org.apache.http.headers=DEBUG