apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-connection
type: Opaque
stringData:
    HOST: "http://guest:guest@broker.default.svc.cluster.local:15672/"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-authentication
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-connection
      key: HOST
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dispatcher-scaler
spec:
  scaleTargetRef:
    name: dispatcher
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 0
  maxReplicaCount: 8 
  triggers:
    - type: rabbitmq
      metadata:
        protocol: http
        queueName: chat.sent
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: rabbitmq-authentication
