apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  enabled_plugins: |
    [rabbitmq_stomp,rabbitmq_management].
  rabbitmq.conf: |
    loopback_users = none
    default_user = guest
    default_pass = guest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-definitions
data:
  definitions.json: |
    {
      "queues": [
        {"name": "chat.sent",            "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "chat.read.in",         "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "chat.typing.in",       "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "chat.delivered",       "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "chat.read.out",        "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "chat.typing.out",      "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "conversation.created", "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic", "x-dead-letter-exchange": "", "x-dead-letter-routing-key": "dead"}},
        {"name": "dead",                 "vhost": "/", "durable": true, "arguments": {"x-queue-type": "classic"}}
      ]
    }
