apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatcher-config
data:
  RABBITMQ_HOST: broker
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
  DYNAMODB_HOST: dynamodb
  DYNAMODB_PORT: "8000"
  DYNAMODB_TABLE: Conversations
  CONVERSATIONS_API_URI: http://conversations:8080/api
